name: brainstormer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.3.3
  google_sign_in: ^5.1.2
  auto_route: ^5.0.4
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.3
  flutter_dotenv: ^5.0.2
  json_serializable: ^6.6.0
  json_annotation: ^4.8.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  retrofit_generator: ^4.2.0
  flutter_gen_runner: ^5.1.0+1
  flutter_launcher_icons: ^0.11.0

flutter:

  assets:
    - .env
    - assets/images/

flutter_icons:
  ios: true
  android: true
  image_path: "assets/app_icon/standard.png"
  image_path_ios: "assets/app_icon/standard.png"
  image_path_android: "assets/app_icon/standard.png"
  adaptive_icon_background: "#006D44"
  adaptive_icon_foreground: "assets/app_icon/standard.png"
  remove_alpha_ios: true


flutter_intl:
  enabled: true
  arb_dir: assets/translations
  class_name: Translations

flutter_gen:
  output: lib/generated/

  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/colors.xml
    outputs:
      class_name: AppColors

analyzer:
  errors:
    invalid_annotation_target: ignore