// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiCMjRPQUZC3SXnhYByDV_Jof4-MiDqro',
    appId: '1:1022657871859:web:5086bfce102792287b1c86',
    messagingSenderId: '1022657871859',
    projectId: 'brainstormer-app',
    authDomain: 'brainstormer-app.firebaseapp.com',
    storageBucket: 'brainstormer-app.appspot.com',
    measurementId: 'G-MBD1V6CJZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUbG4B0-0rqqmaepLRel-XCxN7sNWaX_s',
    appId: '1:1022657871859:android:3c11cbd4184333367b1c86',
    messagingSenderId: '1022657871859',
    projectId: 'brainstormer-app',
    storageBucket: 'brainstormer-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlF1cDZp5ZKMMgG-owizrBSMhorJ7Ytdw',
    appId: '1:1022657871859:ios:6cdeccb1bcb8d8b17b1c86',
    messagingSenderId: '1022657871859',
    projectId: 'brainstormer-app',
    storageBucket: 'brainstormer-app.appspot.com',
    iosClientId: '1022657871859-pj4jhodoie047u4tqn51md1m2kfcli51.apps.googleusercontent.com',
    iosBundleId: 'com.example.brainstormerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlF1cDZp5ZKMMgG-owizrBSMhorJ7Ytdw',
    appId: '1:1022657871859:ios:6cdeccb1bcb8d8b17b1c86',
    messagingSenderId: '1022657871859',
    projectId: 'brainstormer-app',
    storageBucket: 'brainstormer-app.appspot.com',
    iosClientId: '1022657871859-pj4jhodoie047u4tqn51md1m2kfcli51.apps.googleusercontent.com',
    iosBundleId: 'com.example.brainstormerApp',
  );
}
